version: '3.4'

services:
  challenge.konsi.web:
    image: ${DOCKER_REGISTRY-}challengekonsiweb
    build:
      context: .
      dockerfile: src/Challenge.Konsi.Web/Dockerfile
    networks:
      - Challenge.Konsi

  seq:
    image: datalust/seq:latest
    hostname: seq
    container_name: challenge.konsi.seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:80"
    networks:
      - Challenge.Konsi

  rabbitmq:
    image: rabbitmq:3-management
    container_name: challenge.konsi.rabbitmq
    hostname: rabbitmq
    ports:
        - "5672:5672"
        - "15672:15672"
    volumes:
        - data:/usr/share/rabbitmq/data
    environment:
        RABBITMQ_DEFAULT_USER: guest
        RABBITMQ_DEFAULT_PASS: guest
    networks:
      - Challenge.Konsi

  redis:
    image: redis:6.2-alpine
    restart: always
    container_name: challenge.konsi.redis
    hostname: redis
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/usr/share/redis/data
    networks:
      - Challenge.Konsi

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    container_name: challenge.konsi.elasticsearch
    hostname: elasticsearch
    cap_add:
      - IPC_LOCK
    environment:
      - node.name=elasticsearch
      - cluster.name=docker-cluster
      - cluster.initial_master_nodes=elasticsearch
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - Challenge.Konsi


networks:
  Challenge.Konsi:
    driver: bridge

volumes:
  data:
    driver: local
  cache:
    driver: local